<script setup lang="ts">
import { computed, shallowRef } from 'vue'
import GameSwitcher from '../components/research/GameSwitcher.vue'
import { useLottoLab } from '../composables/useLottoLab'
const lab = useLottoLab()
const gameModel = computed({ get: () => lab.game.value, set: value => void lab.selectGame(value) })
const period = shallowRef(100)
const result = shallowRef<ReturnType<typeof lab.runBacktest> | null>(null)
function run() { result.value = lab.runBacktest(period.value) }
</script>
<template><div class="view"><header><div><p class="eyebrow">WALK-FORWARD EVALUATION</p><h1>策略回测</h1><p>每个目标期仅使用此前数据；结果用于观察历史命中分布，不代表未来表现。</p></div><GameSwitcher v-model="gameModel" /></header><section class="card controls"><label>回测窗口<select v-model.number="period"><option :value="50">最近50期</option><option :value="100">最近100期</option><option :value="200">最近200期</option></select></label><button type="button" @click="run">运行走步回测</button></section><section v-if="result" class="card"><div class="summary"><article><span>样本期数</span><strong>{{ result.tested }}</strong></article><article><span>平均主区命中</span><strong>{{ result.averagePrimaryHits.toFixed(2) }}</strong><small>随机基线 {{ result.randomPrimaryHits.toFixed(2) }}</small></article><article><span>平均次区命中</span><strong>{{ result.averageSecondaryHits.toFixed(2) }}</strong><small>随机基线 {{ result.randomSecondaryHits.toFixed(2) }}</small></article></div><p class="notice">LottoLab 不将回测展示为收益率，也不据此作出“提高中奖率”的结论。</p></section><section v-else class="card empty">选择窗口后运行。回测会为每个历史目标期固定种子，并排除该期及未来数据。</section></div></template>
<style scoped>.view{display:grid;gap:1.25rem}header{display:flex;justify-content:space-between;align-items:center;gap:1rem}.eyebrow{margin:0;color:var(--ink-muted);font-size:.67rem;font-weight:800;letter-spacing:.1em}h1{margin:.3rem 0;font-size:1.55rem}p:not(.eyebrow){margin:0;color:var(--ink-soft);font-size:.85rem}.card{border:1px solid var(--line);border-radius:.9rem;padding:1.1rem;background:#fff;box-shadow:var(--card-shadow)}.controls{display:flex;align-items:end;gap:.8rem}.controls label{display:grid;gap:.3rem;color:var(--ink-soft);font-size:.78rem;font-weight:650}.controls select{border:1px solid var(--line);border-radius:.5rem;padding:.55rem;background:#fff;font:inherit}.controls button{border:0;border-radius:.55rem;padding:.65rem .85rem;background:#16253d;color:#fff;font:inherit;font-weight:700;cursor:pointer}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.summary article{padding:.8rem;border-radius:.7rem;background:#f8fafc}.summary span,.summary small{display:block;color:var(--ink-muted);font-size:.72rem}.summary strong{display:block;margin:.35rem 0;font-size:1.45rem}.notice{margin:1rem 0 0!important;padding:.7rem;border-left:3px solid #e9a128;background:#fffbeb;color:#795b1d!important;font-size:.78rem!important}.empty{color:var(--ink-soft);font-size:.85rem}@media(max-width:800px){header{align-items:flex-start;flex-direction:column}.summary{grid-template-columns:1fr}.controls{align-items:start;flex-direction:column}}</style>
