<script setup lang="ts">
import { computed, shallowRef } from 'vue'
import BallNumber from '../components/shared/BallNumber.vue'
import GameSwitcher from '../components/research/GameSwitcher.vue'
import { useLottoLab } from '../composables/useLottoLab'
const lab = useLottoLab(); const query = shallowRef(''); const gameModel = computed({ get: () => lab.game.value, set: value => void lab.selectGame(value) }); const visible = computed(() => lab.draws.value.filter(draw => draw.issue.includes(query.value) || draw.drawDate.includes(query.value)).slice(0, 60))
</script>
<template><div class="view"><header><div><p class="eyebrow">LOCAL DRAW ARCHIVE</p><h1>历史开奖</h1><p>展示已保存的数据源记录及同步状态。</p></div><GameSwitcher v-model="gameModel" /></header><section class="card"><input v-model="query" placeholder="按期号或日期筛选"><div class="table"><div class="table-head"><span>期号 / 日期</span><span>开奖号码</span><span>数据来源</span></div><div v-for="draw in visible" :key="`${draw.game}-${draw.issue}`" class="row"><div><b>{{ draw.issue }}</b><small>{{ draw.drawDate }}</small></div><div class="balls"><BallNumber v-for="number in draw.primaryNumbers" :key="`p-${number}`" :number="number" tone="primary" compact /><BallNumber v-for="number in draw.secondaryNumbers" :key="`s-${number}`" :number="number" tone="secondary" compact /></div><small>{{ draw.source }}</small></div></div></section></div></template>
<style scoped>.view{display:grid;gap:1.25rem}header{display:flex;justify-content:space-between;align-items:center;gap:1rem}.eyebrow{margin:0;color:var(--ink-muted);font-size:.67rem;font-weight:800;letter-spacing:.1em}h1{margin:.3rem 0;font-size:1.55rem}p:not(.eyebrow){margin:0;color:var(--ink-soft);font-size:.85rem}.card{border:1px solid var(--line);border-radius:.9rem;padding:1.1rem;background:var(--surface);box-shadow:var(--card-shadow)}input{width:min(20rem,100%);box-sizing:border-box;border:1px solid var(--line);border-radius:.5rem;padding:.6rem .7rem;font:inherit}.table{margin-top:1rem}.table-head,.row{display:grid;grid-template-columns:10rem 1fr 10rem;gap:1rem;align-items:center;padding:.65rem .4rem;border-bottom:1px solid var(--line)}.table-head{color:var(--ink-muted);font-size:.7rem;font-weight:750}.row b,.row small{display:block}.row b{font-size:.82rem}.row small{color:var(--ink-muted);font-size:.72rem}.balls{display:flex;flex-wrap:wrap;gap:.25rem}@media(max-width:800px){header{align-items:flex-start;flex-direction:column}.table-head,.row{grid-template-columns:1fr}.table-head{display:none}.row{gap:.45rem}}</style>
